name: JailedMC_Citybuild
author: b3n3dkt
version: 1.0.0
main: me.b3n3dkt.Citybuild
api-version: 1.8
depend: [ProtocolLib]

commands:
   fly:
   flyspeed:
   sign:
   gamemode:
     aliases: [gm]
   money:
   eco:
   rang:
   pay:
   discord:
   votekick:
   chatclear:
     aliases: [cc]
   feed:
   globalmute:
   heal:
   invsee:
   lobby:
   rename:
   setspawn:
   spawn:
   vanish:
   enchant:
   event:
   home:
   clearlag:
      aliases: [cl]
   warp:
   job:
   quest:
   shop:
   lag:
   tpa:
   rand: